### ISSUE TITLE
Where to download old versions?

### ISSUE THREAD

**Issue by Bearsden** [splhack/macvim#2]
Hi,

I've been using your version of MacVim, which I found extremely useful. Thanks.

I wonder if you can tell me where I can download older versions. I have the latest version (7.4 (KaoriYa 20150211)) installed, but somehow synchronization between MacVim and Skim for LaTeX stops working. I want to use one of older versions until the issue is resolved.

Best wishes,

Tetsu

**Comment by splhack** [comment]
The previous version is https://github.com/splhack/macvim/releases/tag/20141204

You can find other older versions on https://github.com/splhack/macvim/releases

**Comment by Bearsden** [comment]
Thanks (^_^)/
