### ISSUE TITLE
バージョンが7.4固定で判別できない

### ISSUE THREAD

**Issue by hymmm** [splhack/macvim#3]
組織内でソフトウェアの更新配布を行っているのですが、前のバージョンも今回のリリースも
7.4固定のようです。7.4.<日付> というバージョン番号にできないでしょうか。

**Comment by splhack** [comment]
MacVim.app/Contents/Info.plist CFBundleVersion が日付になっていますのでお試しくださいませ。

**Comment by hymmm** [comment]
なるほど、そちらで判別できそうですね。ありがとうございます、助かります。
