### ISSUE TITLE
Google日本語入力で設定によっては全角スペースが入力出来ない

### ISSUE THREAD

**Issue by pasela** [splhack/macvim#4]
Google日本語入力で「スペースの入力」を「半角」に設定している状態で`Shift+Space`を入力しても全角スペースが入力できなくなりました（半角スペースが入力される）。

「スペースの入力」を「半角」に設定すると、日本語入力がオンの状態でも半角でスペースが入力されて、`Shift+Space`を押すことで全角スペースが入力されるようになるのですが、半角スペースが入力されてしまいます。

この現象が起きたのはMacVim-KaoriYa 20141204からなので、恐らく「10.10 YosemiteでSHIFT+SPACEを効かせるパッチ」というのが関係しているのではないかという気がしています。

OS: 10.9.5 Mavericks
Vim: MacVim-KaoriYa 20141204〜20150304

**Comment by splhack** [comment]
user defaultsにそのパッチをdisableにできる方法を追加しようとおもいます。

    defaults write org.vim.MacVim MMIgnoreShiftSpace -bool FALSE

デフォルトは現在の挙動のままですが、このコマンドラインを実行すれば、以降は従来通りの挙動に戻るはずです。

    diff --git a/src/MacVim/MMAppController.m b/src/MacVim/MMAppController.m
    index 55e3cf7..5d4cf69 100644
    --- a/src/MacVim/MMAppController.m
    +++ b/src/MacVim/MMAppController.m
    @@ -226,6 +226,7 @@ fsEventCallback(ConstFSEventStreamRef streamRef,
     #endif // INCLUDE_OLD_IM_CODE
             [NSNumber numberWithBool:NO],   MMSuppressTerminationAlertKey,
             [NSNumber numberWithBool:YES],  MMNativeFullScreenKey,
    +        [NSNumber numberWithBool:YES],  MMIgnoreShiftSpaceKey,
             nil];
     
         [[NSUserDefaults standardUserDefaults] registerDefaults:dict];
    diff --git a/src/MacVim/MMTextViewHelper.m b/src/MacVim/MMTextViewHelper.m
    index e37ea17..cc7164d 100644
    --- a/src/MacVim/MMTextViewHelper.m
    +++ b/src/MacVim/MMTextViewHelper.m
    @@ -188,7 +188,9 @@ KeyboardInputSourcesEqual(TISInputSourceRef a, TISInputSourceRef b)
             [self doKeyDown:@"\x1e"];
             string = nil;
     #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_10)
    -    } else if ((flags & NSShiftKeyMask) && [string isEqualToString:@" "]) {
    +    } else if ([[NSUserDefaults standardUserDefaults]
    +                boolForKey:MMIgnoreShiftSpaceKey]
    +            && (flags & NSShiftKeyMask) && [string isEqualToString:@" "]) {
             // HACK! for Yosemite - Fix for Shift+Space inputing
             // do nothing
     #endif
    diff --git a/src/MacVim/Miscellaneous.h b/src/MacVim/Miscellaneous.h
    index 52aaaea..de17cb3 100644
    --- a/src/MacVim/Miscellaneous.h
    +++ b/src/MacVim/Miscellaneous.h
    @@ -54,6 +54,7 @@ extern NSString *MMUseInlineImKey;
     #endif // INCLUDE_OLD_IM_CODE
     extern NSString *MMSuppressTerminationAlertKey;
     extern NSString *MMNativeFullScreenKey;
    +extern NSString *MMIgnoreShiftSpaceKey;
     
     
     // Enum for MMUntitledWindowKey
    diff --git a/src/MacVim/Miscellaneous.m b/src/MacVim/Miscellaneous.m
    index 9d719e4..ac2a616 100644
    --- a/src/MacVim/Miscellaneous.m
    +++ b/src/MacVim/Miscellaneous.m
    @@ -46,6 +46,7 @@ NSString *MMUseInlineImKey              = @"MMUseInlineIm";
     #endif // INCLUDE_OLD_IM_CODE
     NSString *MMSuppressTerminationAlertKey = @"MMSuppressTerminationAlert";
     NSString *MMNativeFullScreenKey         = @"MMNativeFullScreen";
    +NSString *MMIgnoreShiftSpaceKey         = @"MMIgnoreShiftSpace";

**Comment by splhack** [comment]
お試しくださいませ
https://github.com/splhack/macvim/releases/tag/20150305

**Comment by pasela** [comment]
期待通りの動作になりました！

でもこれって、Yosemiteにしたら`Shift+Space`が効かないという当初の問題に戻ってしまうのですかね。
つらい……。

**Comment by splhack** [comment]
Yosemiteでは以下の挙動になるので問題ないかと思います。

デフォルト(MMIgnoreShiftSpaceKey=TRUE)

|                               |スペース入力:入力モードに従う|スペース入力:半角|
|--------------------------|-------------------------------------------|-------------------------|
|スペース                 |全角スペース                              |半角スペース        |
|シフト＋スペース  |半角スペース                              |**半角**スペース        |

MMIgnoreShiftSpaceKey=FALSE

|                               |スペース入力:入力モードに従う|スペース入力:半角|
|--------------------------|-------------------------------------------|-------------------------|
|スペース                 |全角スペース                              |半角スペース        |
|シフト＋スペース  |(**何も起きない**)                        |**全角**スペース        |
