### ISSUE TITLE
GUI で sudo が使えない

### ISSUE THREAD

**Issue by delphinus35** [splhack/macvim#5]
いつの頃からか、gvim 上で sudo を使うとエラーメッセージが表示されるようになりました。

```
:w !sudo tee %
sudo: no tty present and no askpass program specified
```

ググると [`$SUDO_ASKPASS` を設定しろ][sudo]とあるのですが、macvim-kaoriya のソースを grep すると `$SSH_ASKPASS` という微妙に違う変数が[設定してあります][ask]。

[sudo]: http://sanrinsha.lolipop.jp/blog/2014/03/gui_macvim_sudo.html
[ask]: https://github.com/splhack/macvim/blob/master/src/MacVim/gvimrc#L294

`~/.vim/gvimrc` にて

```vim
let $SUDO_ASKPASS=$SSH_ASKPASS
```

と設定すると、確かに問題なく動くようになるのですが、標準添付の `gvimrc` にて `$SSH_ASKPASS` という変数名になっているのはなぜなのでしょうか？（あるいは、これは全く別の用途の変数なのか……）

**Comment by delphinus35** [comment]
補足: 以上の動作は MacVim-KaoriYa 20150707 版で確認しました。

**Comment by splhack** [comment]
ありがとうございます。$SSH_ASKPASSは、opensshでaskpassスクリプトを起動する設定なのです。
