### ISSUE TITLE
Russian lang incorrectly displayed

### ISSUE THREAD

**Issue by nooks** [splhack/macvim#6]
http://cl.ly/image/080k0A1u0f2Y

**Comment by splhack** [comment]
What is the issue? I have totally no idea about Russian. And you should share a minimum text file in order to reproduce the issue.

**Comment by nooks** [comment]
After each letter of the virtual spaces!
Привет, меня зовут Максим! Я родился в Новомосковске!

**Comment by splhack** [comment]
:set ambiwidth=single

**Comment by nooks** [comment]
Thanks!
