### ISSUE TITLE
No detect background color

### ISSUE THREAD

**Issue by nooks** [splhack/macvim#7]
First launch, colorscheme badwolf
http://cl.ly/image/3P1b1w3Q0a1S
After entering the command ":colorscheme badwolf" It becomes normal
http://cl.ly/image/1Q1j3O0Q0a2U

Video http://cl.ly/2B0M301W0e0J

**Comment by splhack** [comment]
I don't understand you.

If you want to set `colorscheme` in rc file, you should write `colorscheme` line in `.gvimrc`.

**Comment by nooks** [comment]
Thanks!
